Remove Matek 😤
apetavern/web pull request #4
Opened 2024-02-22 23:37 UTC by Nolankicks

2024-02-22 23:38 UTC, matekdev approved these changes

2024-02-22 23:42 UTC, trundlr commented
Can you please clean up matek's avatar as well? And then add cameron and eEight to the team too.

2024-02-22 23:42 UTC, trundlr requested changes
See comment above.

2024-02-23 00:16 UTC, merged

2024-02-23 00:16 UTC, trundlr commented
Thanks for your contribution!